### ISSUE TITLE
IPC: Adapt the genesis deployment of the gateway to use diamond implementation

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/fendermint#168]
We recently implemented a diamond architecture for the gateway (see [deployment](https://github.com/consensus-shipyard/ipc-solidity-actors/blob/dev/scripts/deploy-gateway.template)), and we should adapt the genesis deployment of the actor implemented in https://github.com/consensus-shipyard/fendermint/pull/159 to work with this new contract architecture.

**Comment by aakoshh** [comment]
@adlrocha I'll hopefully be able to figure it out from the new deployment script, which I have not looked at under a magnifier, but I'm trying to understand how people are supposed to deploy subnets with the diamond. 

The `SubnetActor` wasn't deployed in Genesis because it will be a different actor for each subnet users create, even though the code is the same. What happens now that it's been split into a diamond and two facets? Do you deploy 3 contracts? Or should the facets be deployed in Genesis? How does it work with addresses?
