### ISSUE TITLE
Bootstrap child subnet

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/fendermint#301]
Related: https://github.com/consensus-shipyard/ipc-solidity-actors/pull/223

Once the minimum requirements set by a subnet to bootstrap (mainly minimum number of validators, and minimum collateral in the reference implementation) are fulfilled, the subnet actor in the parent emits an event to notify that the infrastructure for the subnet can be spawned. This event can be used to create deterministically the Fendermint genesis, setting the initial validators of the subnet to the ones determined by the parent, and thus deploying the infrastructure for the child subnet according to the information in the parent.

The genesis of the child subnet should: 
- Initialize the gateway of the with the initial validators that have bootstrapped the network (from there on, updates to membership are handled through top-down proof-of-finality). 
- Initialize  the initial validators in Fendermint so they are picked up right away to start creating new blocks.

**Comment by aakoshh** [comment]
My reading of this issue is that what should happen within its scope is limited to passing the initial validators to the gateway contract so that it can initialise the active validator set. This should already have happened in https://github.com/consensus-shipyard/fendermint/issues/148 but I didn't realise or know it at the time.

The beginning of the story with regards to the bootstrap events can be done as part of #306

**Comment by aakoshh** [comment]
The problem with the above way of hashing public keys to match them up with the accounts is that we wanted to keep the option of having an address which separate from the public key. That suggests the whole initial validator set needs to be repeated inside the IPC gateway configuration :disappointed:
