### ISSUE TITLE
IPC: Initial `fund` for validators to be able to sign checkpoints

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/fendermint#347]
## Background

While this bug was found in Fendermint, it mainly involves changes in the contract. When we bootstrap a new child subnet, validators currently don't have any funds, which means that whenever is time to sign a new checkpoint they won't have enough funds to call the contract, and the call will be reverted.

## Proposal

The proposal is to automatically create a `fund` message for a specific amount of tokens(0.5FIL?) whenever a validator joins. This message will be propagated to the child to populate the validator's address so it can start signing checkpoints. From there on, validators should ensure that they always have enough balance to sign checkpoints, otherwise they won't be able to sign new checkpoints.

**Comment by aakoshh** [comment]
I'll repeat some of my comments on this issue:
* We expect bottom-up checkpoints at regular intervals, and these checkpoints _will_ be created in the child subnet ledger, regardless of whether the validators are able to sign them or not. 
* The child nodes follow the parent node and they are able to execute top-down messages at any time. 
* Therefore even if validators start with 0 balance, they are able to fund themselves from the parent and then sign incomplete checkpoints. 

Of course, that would be very poor UX; ideally they would have their starting balance, and so would anybody else interested in participating in the subnet. 

Although it's appealing if `join` would automatically `fund` a validator, I would actually try to avoid fusing these two, and especially to pick constants that look sensible now, but we don't know if they are appropriate values. Like the 0.5 FIL might allow you to send signatures to a handful of checkpoints, but if checkpoints really cost anything (which they currently don't, because anyone can set the price to 0 and not pay anything), then we either need to refund them from the fees (TBD) or they have to keep funding themselves (leading to almost the same UX). 

What I'd propose is that we take this a little further and handle `fund` and `release` on subnets _before_ they are bootstrapped similarly to how we handle `join`, `stake`, `leave` and `unstake`: 
1. The contract should maintain a genesis balance that gets increased in `fund` and it can even send the tokens back in `release` as long as the subnet is not yet bootstrapped. 
2. After it's bootstrapped, `fund` and `release` send cross messages to the subnet. The genesis account balances don't have to be sent as messages.
3. The CLI tool Alfonso developed should query the genesis balances and put them into the `genesis.json` file, thus establishing accounts for the validators or anybody else who funded early. 

To make it into a more convenient experience for validators, the `ipc-cli` tool should have a `--collateral` and a `--fund` parameter for its `join` command and send a `fund` and a `join` message as well to the subnet actor. That way validators are reminded to pick a value and are reminded to do so.

**Comment by adlrocha** [comment]
OK, so what I am planning for M2.5 is the following (@aakoshh, let me know what you think).
* Allow validators to optionally send some funds to the subnet after joining through the `ipc-cli`. 
* If the subnet hasn't been bootstrapped yet, the funds are added to the `GenesisValidator` struct and added to the balance of the validators in the child's subnet genesis. This is performed through a single call to `join` in the contract. The contract is the one responsible for adding the funds into the `GenesisValidator` struct.
* When a validator joins to an already bootstrapped network, what the `ipc-cli` does under the hood is to perform a call to `join` with the corresponding amount of collateral, and then making a call to `fund` to trigger a top-down message that will add balance to their address in the child subnet.

**Comment by aakoshh** [comment]
> If the subnet hasn't been bootstrapped yet, the funds are added to the GenesisValidator struct and added to the balance of the validators in the child's subnet genesis. 

That sounds good :+1: 

> This is performed through a single call to join in the contract. The contract is the one responsible for adding the funds into the GenesisValidator struct.

I don't understand this one. Why not modify the `fund` so that it adds to the genesis balances if the contract isn't bootstrapped?

**Comment by adlrocha** [comment]
> Why not modify the fund so that it adds to the genesis balances if the contract isn't bootstrapped?

Yes, that is actually cleaner. I will pick this one up then.
